[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet JapaneseFlashcardApi.dll"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[experimental]
configAsCode = true
