[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet JapaneseFlashcardApi.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[experimental]
configAsCode = true
